"""Unit tests for module_1: each public method tested independently."""
# Generated by Cursor Agent
# 1/29/2026

import tempfile
import unittest
from pathlib import Path

from src import module_1

# Paths to integration test data (relative to project root; run tests from project root)
CASE_INIT_PATH = Path("integration_tests/module_1/case_inits/case_init.json")
RULES_PATH = Path("integration_tests/module_1/rules.json")


def _tiny_constraints():
    """Minimal game_constraints (same shape as rules['game_constraints']) for grounding tests."""
    return {
        "suspects": ["Alice"],
        "rooms": ["Study"],
        "weapons": ["Candlestick"],
        "time_points": ["9pm"],
    }


# --- read_case_init ---


class TestReadCaseInit(unittest.TestCase):
    """Tests for module_1.read_case_init (loads case_init.json, returns kb_evidence + witness_knowledge + metadata)."""

    def test_returns_dict_with_kb_evidence_witness_knowledge_and_metadata(self):
        """read_case_init(path) should return a dict with keys 'kb_evidence', 'witness_knowledge', and 'metadata'."""
        result = module_1.read_case_init(CASE_INIT_PATH)
        self.assertIn("kb_evidence", result)
        self.assertIn("witness_knowledge", result)
        self.assertIn("metadata", result)
        self.assertIsInstance(result["kb_evidence"], dict)
        self.assertIsInstance(result["witness_knowledge"], dict)
        self.assertIsInstance(result["metadata"], dict)

    def test_evidence_dicts_map_propositions_to_bool(self):
        """kb_evidence and witness_knowledge should map proposition names (str) to True or False."""
        result = module_1.read_case_init(CASE_INIT_PATH)
        for evidence_dict in (result["kb_evidence"], result["witness_knowledge"]):
            for key, val in evidence_dict.items():
                self.assertIsInstance(key, str)
                self.assertIn(val, (True, False))

    def test_nonexistent_path_raises(self):
        """read_case_init should raise FileNotFoundError when the file does not exist."""
        # We are testing that a missing file path results in FileNotFoundError, not a silent failure.
        with self.assertRaises(FileNotFoundError):
            module_1.read_case_init("nonexistent_case_init.json")


# --- read_rules ---


class TestReadRules(unittest.TestCase):
    """Tests for module_1.read_rules (loads rules.json)."""

    def test_returns_dict_with_rules_and_game_constraints(self):
        """read_rules(path) should return a dict with 'rules', 'game_constraints', and 'metadata'."""
        # We are testing that the return value has the expected top-level keys and that rules is a list, game_constraints a dict.
        result = module_1.read_rules(RULES_PATH)
        self.assertIn("rules", result)
        self.assertIn("game_constraints", result)
        self.assertIn("metadata", result)
        self.assertIsInstance(result["rules"], list)
        self.assertIsInstance(result["game_constraints"], dict)

    def test_each_rule_has_id_if_then(self):
        """Each entry in rules should have keys 'id', 'if', and 'then'."""
        # We are testing that every rule object has the required keys for inference (id, if, then).
        result = module_1.read_rules(RULES_PATH)
        for rule in result["rules"]:
            self.assertIn("id", rule)
            self.assertIn("if", rule)
            self.assertIn("then", rule)

    def test_nonexistent_path_raises(self):
        """read_rules should raise FileNotFoundError when the file does not exist."""
        # We are testing that a missing rules file results in FileNotFoundError.
        with self.assertRaises(FileNotFoundError):
            module_1.read_rules("nonexistent_rules.json")


# --- ground_rule ---


class TestGroundRule(unittest.TestCase):
    """Tests for module_1.ground_rule (one rule template -> list of concrete rules)."""

    def test_returns_list(self):
        """ground_rule(rule, game_constraints) should return a list (of concrete rules)."""
        # We are testing that ground_rule returns a list (one entry per substitution of placeholders).
        rule = {"id": "R1", "if": ["At_PERSON_ROOM_TIME"], "then": "At_PERSON_ROOM_TIME"}
        out = module_1.ground_rule(rule, _tiny_constraints())
        self.assertIsInstance(out, list)

    def test_each_element_has_if_and_then(self):
        """Each grounded rule in the list should have 'if' and 'then' keys (no placeholders)."""
        # We are testing that each grounded rule has if/then and that placeholders (PERSON, ROOM, TIME) were replaced with concrete values.
        rule = {"id": "R1", "if": ["At_PERSON_ROOM_TIME"], "then": "At_PERSON_ROOM_TIME"}
        out = module_1.ground_rule(rule, _tiny_constraints())
        for g in out:
            self.assertIn("if", g)
            self.assertIn("then", g)
            for prop in g["if"]:
                self.assertTrue(
                    "PERSON" not in prop or "Alice" in prop,
                    f"placeholder PERSON not replaced in {prop}",
                )
                self.assertTrue(
                    "ROOM" not in prop or "Study" in prop,
                    f"placeholder ROOM not replaced in {prop}",
                )
                self.assertTrue(
                    "TIME" not in prop or "9pm" in prop,
                    f"placeholder TIME not replaced in {prop}",
                )


# --- ground_all_rules ---


class TestGroundAllRules(unittest.TestCase):
    """Tests for module_1.ground_all_rules (calls ground_rule for each rule)."""

    def test_returns_list(self):
        """ground_all_rules(rules, game_constraints) should return a list."""
        # We are testing that ground_all_rules returns a single list (all grounded rules concatenated).
        rules = [{"id": "R1", "if": ["Alibi_PERSON_TIME"], "then": "NOT_Culprit_PERSON_TIME"}]
        out = module_1.ground_all_rules(rules, _tiny_constraints())
        self.assertIsInstance(out, list)

    def test_collects_from_all_rules(self):
        """The returned list should be the concatenation of grounding each rule (length >= 0)."""
        # We are testing that the result has at least as many items as grounding one rule (length >= 0).
        rules = [{"id": "R1", "if": ["Alibi_PERSON_TIME"], "then": "X"}]
        out = module_1.ground_all_rules(rules, _tiny_constraints())
        self.assertGreaterEqual(len(out), 0)


# --- build_kb ---


class TestBuildKb(unittest.TestCase):
    """Tests for module_1.build_kb (initial_evidence -> KB dict)."""

    def test_returns_dict(self):
        """build_kb(initial_evidence) should return a dict."""
        # We are testing that build_kb returns a dict (the knowledge base).
        out = module_1.build_kb({"At_Alice_Study_9pm": True})
        self.assertIsInstance(out, dict)

    def test_contains_only_true_from_initial_evidence(self):
        """The returned KB should contain only propositions that are True in initial_evidence (absence = false)."""
        # KB stores only TRUE; false propositions are not stored and cannot imply or chain.
        evidence = {"At_Alice_Study_9pm": True, "Weapon_Candlestick_Study": False}
        kb = module_1.build_kb(evidence)
        self.assertIs(kb.get("At_Alice_Study_9pm"), True)
        self.assertNotIn("Weapon_Candlestick_Study", kb)


# --- rule_premises_met ---


class TestRulePremisesMet(unittest.TestCase):
    """Tests for module_1.rule_premises_met (grounded_rule['if'] all true in kb?)."""

    def test_true_when_all_premises_in_kb_as_true(self):
        """rule_premises_met should return True when every 'if' proposition is in kb with value True."""
        # We are testing that the function returns True when all premises of the rule are already in the KB as True.
        grounded = {"if": ["At_Alice_Study_9pm", "Weapon_Candlestick_Study"], "then": "Suspect_Alice"}
        kb = {"At_Alice_Study_9pm": True, "Weapon_Candlestick_Study": True}
        self.assertIs(module_1.rule_premises_met(grounded, kb), True)

    def test_false_when_one_premise_missing_from_kb(self):
        """rule_premises_met should return False when any 'if' proposition is not in kb."""
        # We are testing that the function returns False when at least one premise is missing from the KB.
        grounded = {"if": ["At_Alice_Study_9pm", "Weapon_Candlestick_Study"], "then": "Suspect_Alice"}
        kb = {"At_Alice_Study_9pm": True}
        self.assertIs(module_1.rule_premises_met(grounded, kb), False)

    def test_false_when_premise_absent_from_kb(self):
        """rule_premises_met should return False when a premise is absent (false; KB stores only True)."""
        # Absence means false; the premise must be present (true) in the KB to fire.
        grounded = {"if": ["At_Alice_Study_9pm"], "then": "X"}
        kb = {}
        self.assertIs(module_1.rule_premises_met(grounded, kb), False)


# --- apply_rule ---


class TestApplyRule(unittest.TestCase):
    """Tests for module_1.apply_rule (if premises met, add grounded_rule['then'] to kb)."""

    def test_adds_then_to_kb_when_premises_met(self):
        """When premises are met, apply_rule should add grounded_rule['then'] to kb and return True."""
        # We are testing that when all premises hold, the conclusion is added to the KB and the function returns True.
        grounded = {"if": ["At_Alice_Study_9pm"], "then": "HadAccess_Alice_Candlestick"}
        kb = {"At_Alice_Study_9pm": True}
        changed = module_1.apply_rule(grounded, kb)
        self.assertIs(changed, True)
        self.assertIs(kb.get("HadAccess_Alice_Candlestick"), True)

    def test_does_nothing_when_premises_not_met(self):
        """When premises are not met, apply_rule should not add anything and return False."""
        # We are testing that when a premise is missing, the KB is unchanged and the function returns False.
        grounded = {"if": ["At_Alice_Study_9pm"], "then": "HadAccess_Alice_Candlestick"}
        kb = {}
        changed = module_1.apply_rule(grounded, kb)
        self.assertIs(changed, False)
        self.assertNotIn("HadAccess_Alice_Candlestick", kb)

    def test_records_contradiction_when_then_is_contradiction(self):
        """When grounded_rule['then'] is 'CONTRADICTION', apply_rule should add it to kb and return True."""
        # We are testing that contradiction rules add CONTRADICTION to the KB and return True so inference can stop.
        grounded = {"if": ["Alibi_Alice_9pm", "Culprit_Alice_9pm"], "then": "CONTRADICTION"}
        kb = {"Alibi_Alice_9pm": True, "Culprit_Alice_9pm": True}
        changed = module_1.apply_rule(grounded, kb)
        self.assertIs(changed, True)
        self.assertIs(kb.get("CONTRADICTION"), True)


# --- infer ---


class TestInfer(unittest.TestCase):
    """Tests for module_1.infer (repeatedly apply grounded rules until fixpoint or CONTRADICTION)."""

    def test_modifies_kb_in_place(self):
        """infer(kb, grounded_rules) should modify kb in place (same dict reference)."""
        # We are testing that infer updates the given kb dict (no new dict returned).
        kb = {"At_Alice_Study_9pm": True}
        grounded = [{"if": ["At_Alice_Study_9pm"], "then": "HadAccess_Alice_Candlestick"}]
        module_1.infer(kb, grounded)
        self.assertIn("At_Alice_Study_9pm", kb)

    def test_with_empty_rules_leaves_kb_unchanged(self):
        """With an empty grounded_rules list, kb should be unchanged except for initial contents."""
        # We are testing that with no rules to apply, the KB is left exactly as it was.
        kb = {"At_Alice_Study_9pm": True}
        module_1.infer(kb, [])
        self.assertEqual(kb, {"At_Alice_Study_9pm": True})


# --- has_contradiction ---


class TestHasContradiction(unittest.TestCase):
    """Tests for module_1.has_contradiction (is 'CONTRADICTION' in kb?)."""

    def test_true_when_contradiction_in_kb(self):
        """has_contradiction(kb) should return True when 'CONTRADICTION' is in kb (as key)."""
        # We are testing that the function returns True when the KB contains a CONTRADICTION (e.g. from a contradiction rule).
        kb = {"At_Alice_Study_9pm": True, "CONTRADICTION": True}
        self.assertIs(module_1.has_contradiction(kb), True)

    def test_false_when_no_contradiction_in_kb(self):
        """has_contradiction(kb) should return False when CONTRADICTION is not in kb."""
        # We are testing that the function returns False when no contradiction has been inferred.
        kb = {"At_Alice_Study_9pm": True}
        self.assertIs(module_1.has_contradiction(kb), False)


# --- generate_random_case ---


class TestGenerateRandomCase(unittest.TestCase):
    """Tests for module_1.generate_random_case (generate random Clue case)."""

    def test_returns_dict_with_expected_keys(self):
        """generate_random_case should return dict with kb_evidence, witness_knowledge, metadata."""
        result = module_1.generate_random_case(RULES_PATH, seed=42)
        self.assertIn("kb_evidence", result)
        self.assertIn("witness_knowledge", result)
        self.assertIn("metadata", result)
        self.assertIsInstance(result["kb_evidence"], dict)
        self.assertIsInstance(result["witness_knowledge"], dict)
        self.assertIsInstance(result["metadata"], dict)

    def test_metadata_contains_solution_info(self):
        """Metadata should contain _solution_culprit, _solution_weapon, _solution_room."""
        result = module_1.generate_random_case(RULES_PATH, seed=42)
        metadata = result["metadata"]
        self.assertIn("_solution_culprit", metadata)
        self.assertIn("_solution_weapon", metadata)
        self.assertIn("_solution_room", metadata)
        self.assertIn("_solution_time", metadata)
        # Solution values should be from game_constraints
        rules = module_1.read_rules(RULES_PATH)
        suspects = rules["game_constraints"]["suspects"]
        weapons = rules["game_constraints"]["weapons"]
        rooms = rules["game_constraints"]["rooms"]
        self.assertIn(metadata["_solution_culprit"], suspects)
        self.assertIn(metadata["_solution_weapon"], weapons)
        self.assertIn(metadata["_solution_room"], rooms)

    def test_reproducible_with_seed(self):
        """Same seed should produce same case."""
        case1 = module_1.generate_random_case(RULES_PATH, seed=123)
        case2 = module_1.generate_random_case(RULES_PATH, seed=123)
        self.assertEqual(case1["metadata"]["_solution_culprit"], case2["metadata"]["_solution_culprit"])
        self.assertEqual(case1["metadata"]["_solution_weapon"], case2["metadata"]["_solution_weapon"])
        self.assertEqual(case1["metadata"]["_solution_room"], case2["metadata"]["_solution_room"])

    def test_different_seeds_produce_different_cases(self):
        """Different seeds should produce different cases (usually)."""
        case1 = module_1.generate_random_case(RULES_PATH, seed=1)
        case2 = module_1.generate_random_case(RULES_PATH, seed=2)
        # At least one solution component should differ (very likely)
        solutions_differ = (
            case1["metadata"]["_solution_culprit"] != case2["metadata"]["_solution_culprit"]
            or case1["metadata"]["_solution_weapon"] != case2["metadata"]["_solution_weapon"]
            or case1["metadata"]["_solution_room"] != case2["metadata"]["_solution_room"]
        )
        self.assertTrue(solutions_differ, "Different seeds should produce different cases")

    def test_no_culprit_facts_in_output(self):
        """Case file facts (Culprit_*) should not appear in kb_evidence or witness_knowledge."""
        result = module_1.generate_random_case(RULES_PATH, seed=42)
        all_facts = {**result["kb_evidence"], **result["witness_knowledge"]}
        culprit_facts = [k for k in all_facts.keys() if k.startswith("Culprit_")]
        self.assertEqual(len(culprit_facts), 0, "Culprit facts should be hidden (case file)")

    def test_victim_found_only_in_hall(self):
        """VictimFound should only be True in the Hall (body discovery location)."""
        result = module_1.generate_random_case(RULES_PATH, seed=42)
        all_facts = {**result["kb_evidence"], **result["witness_knowledge"]}
        for room in module_1.read_rules(RULES_PATH)["game_constraints"]["rooms"]:
            fact = f"VictimFound_{room}"
            if fact in all_facts:
                expected = room == "Hall"
                self.assertEqual(
                    all_facts[fact],
                    expected,
                    f"VictimFound_{room} should be {expected} (body discovery room is Hall)",
                )

    def test_respects_kb_ratio(self):
        """kb_evidence should contain approximately kb_ratio of facts."""
        result = module_1.generate_random_case(RULES_PATH, seed=42, kb_ratio=0.3)
        total_facts = len(result["kb_evidence"]) + len(result["witness_knowledge"])
        kb_ratio_actual = len(result["kb_evidence"]) / total_facts if total_facts > 0 else 0
        # Allow some tolerance due to rounding
        self.assertAlmostEqual(kb_ratio_actual, 0.3, delta=0.1)

    def test_murder_weapon_in_murder_room(self):
        """Murder weapon should be placed in the murder room."""
        result = module_1.generate_random_case(RULES_PATH, seed=42)
        solution_weapon = result["metadata"]["_solution_weapon"]
        solution_room = result["metadata"]["_solution_room"]
        all_facts = {**result["kb_evidence"], **result["witness_knowledge"]}
        weapon_fact = f"Weapon_{solution_weapon}_{solution_room}"
        self.assertIn(weapon_fact, all_facts)
        self.assertTrue(all_facts[weapon_fact], f"Murder weapon {solution_weapon} should be in murder room {solution_room}")


# --- run_random_case ---


class TestRunRandomCase(unittest.TestCase):
    """Tests for module_1.run_random_case (generate random case and run pipeline)."""

    def test_creates_output_files(self):
        """run_random_case should create evidence_found.json and questionable_evidence_report.txt."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            output_dir = Path(tmp_dir)
            result = module_1.run_random_case(RULES_PATH, output_dir, seed=42)
            evidence_path = output_dir / "evidence_found.json"
            report_path = output_dir / "questionable_evidence_report.txt"
            self.assertTrue(evidence_path.exists(), "evidence_found.json should be created")
            self.assertTrue(report_path.exists(), "questionable_evidence_report.txt should be created")

    def test_returns_case_data_with_solution(self):
        """run_random_case should return case data including solution info."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            result = module_1.run_random_case(RULES_PATH, Path(tmp_dir), seed=42)
            self.assertIn("kb_evidence", result)
            self.assertIn("witness_knowledge", result)
            self.assertIn("metadata", result)
            self.assertIn("_solution_culprit", result["metadata"])


if __name__ == "__main__":
    unittest.main()
